# Generated by Django 4.2.7 on 2025-09-08 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('intervention_type', models.CharField(choices=[('inspection', 'Inspection'), ('repair', 'Réparation'), ('maintenance', 'Maintenance'), ('emergency', 'Urgence'), ('other', 'Autre')], default='inspection', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Planifiée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('postponed', 'Reportée')], default='scheduled', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=20)),
                ('scheduled_date', models.DateTimeField(verbose_name='Date planifiée')),
                ('estimated_duration', models.DurationField(blank=True, null=True, verbose_name='Durée estimée')),
                ('actual_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de début réelle')),
                ('actual_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin réelle')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Localisation')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('materials_needed', models.TextField(blank=True, null=True, verbose_name='Matériel nécessaire')),
                ('special_instructions', models.TextField(blank=True, null=True, verbose_name='Instructions spéciales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interventions', to=settings.AUTH_USER_MODEL, verbose_name='Technicien assigné')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interventions', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='clients.clientsite')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='InterventionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('estimated_duration', models.DurationField(blank=True, null=True, verbose_name='Durée estimée')),
                ('actual_duration', models.DurationField(blank=True, null=True, verbose_name='Durée réelle')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Débuté à')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé à')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='interventions.intervention')),
            ],
            options={
                'verbose_name': "Tâche d'intervention",
                'verbose_name_plural': "Tâches d'intervention",
                'ordering': ['intervention', 'order'],
            },
        ),
        migrations.CreateModel(
            name='InterventionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('is_internal', models.BooleanField(default=True, verbose_name='Note interne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_notes', to='interventions.intervention')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='interventions.interventiontask')),
            ],
            options={
                'verbose_name': "Note d'intervention",
                'verbose_name_plural': "Notes d'intervention",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterventionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('document_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo'), ('audio', 'Audio'), ('report', 'Rapport'), ('invoice', 'Facture'), ('other', 'Autre')], default='photo', max_length=20)),
                ('file', models.FileField(upload_to='intervention_documents/', verbose_name='Fichier')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Localisation')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='interventions.intervention')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='interventions.interventiontask')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Document d'intervention",
                'verbose_name_plural': "Documents d'intervention",
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
