# Generated by Django 4.2.7 on 2025-09-07 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='Report Title')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(default=dict, verbose_name='Report Data')),
                ('export_formats', models.JSONField(default=list, verbose_name='Available Export Formats')),
                ('last_exported', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intervention Report',
                'verbose_name_plural': 'Intervention Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Section Title')),
                ('section_type', models.CharField(choices=[('text', 'Text Field'), ('textarea', 'Long Text'), ('checklist', 'Checklist'), ('radio', 'Radio Buttons'), ('select', 'Dropdown'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'Date & Time'), ('photo', 'Photo'), ('video', 'Video'), ('audio', 'Audio'), ('sketch', 'Sketch/Drawing'), ('signature', 'Digital Signature'), ('score', 'Score/Rating'), ('calculation', 'Calculation'), ('location', 'GPS Location'), ('file', 'File Upload')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_required', models.BooleanField(default=False, verbose_name='Required')),
                ('is_conditional', models.BooleanField(default=False, verbose_name='Conditional Field')),
                ('configuration', models.JSONField(default=dict, verbose_name='Section Configuration')),
                ('condition_field', models.CharField(blank=True, max_length=100, verbose_name='Condition Field')),
                ('condition_value', models.CharField(blank=True, max_length=200, verbose_name='Condition Value')),
                ('condition_operator', models.CharField(default='equals', max_length=10, verbose_name='Condition Operator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report Section',
                'verbose_name_plural': 'Report Sections',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('template_type', models.CharField(choices=[('standard', 'Standard'), ('emergency', 'Emergency'), ('maintenance', 'Maintenance'), ('inspection', 'Inspection'), ('custom', 'Custom')], default='standard', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public Template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.JSONField(default=dict, verbose_name='Template Configuration')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signature_type', models.CharField(choices=[('author', 'Author Signature'), ('reviewer', 'Reviewer Signature'), ('client', 'Client Signature'), ('approver', 'Approver Signature')], max_length=20)),
                ('signature_data', models.TextField(verbose_name='Signature Data (Base64)')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='reports/signatures/%Y/%m/%d/')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('verification_hash', models.CharField(blank=True, max_length=64, verbose_name='Verification Hash')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='reports.interventionreport')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Signature',
                'verbose_name_plural': 'Report Signatures',
                'ordering': ['-signed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSectionData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, verbose_name='Section Value')),
                ('data', models.JSONField(default=dict, verbose_name='Section Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_data', to='reports.interventionreport')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_instances', to='reports.reportsection')),
            ],
            options={
                'verbose_name': 'Report Section Data',
                'verbose_name_plural': 'Report Section Data',
                'unique_together': {('report', 'section')},
            },
        ),
        migrations.AddField(
            model_name='reportsection',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.reporttemplate'),
        ),
        migrations.CreateModel(
            name='ReportMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('audio', 'Audio'), ('sketch', 'Sketch'), ('file', 'File')], max_length=20)),
                ('file', models.FileField(upload_to='reports/media/%Y/%m/%d/', verbose_name='Media File')),
                ('filename', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('file_size', models.PositiveIntegerField(verbose_name='File Size (bytes)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME Type')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Media Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('annotation', models.TextField(blank=True, verbose_name='Annotation')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='Altitude')),
                ('captured_at', models.DateTimeField(blank=True, null=True, verbose_name='Captured At')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Height')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='reports.reportsectiondata')),
            ],
            options={
                'verbose_name': 'Report Media',
                'verbose_name_plural': 'Report Media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('section_added', 'Section Added'), ('section_modified', 'Section Modified'), ('section_deleted', 'Section Deleted'), ('media_added', 'Media Added'), ('media_removed', 'Media Removed'), ('status_changed', 'Status Changed'), ('signed', 'Signed'), ('exported', 'Exported'), ('shared', 'Shared')], max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='Field Name')),
                ('old_value', models.TextField(blank=True, verbose_name='Old Value')),
                ('new_value', models.TextField(blank=True, verbose_name='New Value')),
                ('change_summary', models.TextField(blank=True, verbose_name='Change Summary')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reports.interventionreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report History',
                'verbose_name_plural': 'Report History',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('html', 'HTML'), ('json', 'JSON'), ('xml', 'XML')], max_length=10)),
                ('template_used', models.CharField(blank=True, max_length=200, verbose_name='Template Used')),
                ('export_settings', models.JSONField(default=dict, verbose_name='Export Settings')),
                ('file_path', models.CharField(max_length=500, verbose_name='File Path')),
                ('file_size', models.PositiveIntegerField(verbose_name='File Size (bytes)')),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('is_shared', models.BooleanField(default=False, verbose_name='Shared')),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('share_token', models.CharField(blank=True, max_length=64, verbose_name='Share Token')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('exported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='reports.interventionreport')),
            ],
            options={
                'verbose_name': 'Report Export',
                'verbose_name_plural': 'Report Exports',
                'ordering': ['-exported_at'],
            },
        ),
        migrations.AddField(
            model_name='interventionreport',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.reporttemplate'),
        ),
    ]
